import jwt from 'jsonwebtoken';
import dotenv from 'dotenv'; dotenv.config();
const SECRET = process.env.JWT_SECRET || 'change-me-in-production';
const API = 'http://localhost:3001';
const ownerLogin = await (await fetch(API + '/api/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: 'demo@aisdr.dev', password: 'demo1234' }) })).json();
const OH = { Authorization: 'Bearer ' + ownerLogin.token, 'Content-Type': 'application/json' };
const { PrismaClient } = await import('@prisma/client'); const p = new PrismaClient();
const m = await p.user.findFirst({ where: { email: 'member@aisdr.dev' }, select: { id: true, orgId: true, email: true, role: true, tokenVersion: true } });
const memberToken = jwt.sign({ userId: m.id, orgId: m.orgId, email: m.email, role: m.role, tv: m.tokenVersion }, SECRET, { expiresIn: '7d' });
const MH = { Authorization: 'Bearer ' + memberToken, 'Content-Type': 'application/json' };
const deals = await (await fetch(API + '/api/records?objectKey=deals&limit=100', { headers: OH })).json();
const acme = deals.records.find((r) => r.displayName === 'Acme — New Business');
console.log('Acme id', acme.id, 'current stage', acme.values?.stage?.value);
const o1 = await fetch(API + '/api/records/' + acme.id + '/move', { method: 'PATCH', headers: OH, body: JSON.stringify({ attributeKey: 'stage', value: 'meeting' }) }); const j1 = await o1.json(); console.log('OWNER move->meeting:', o1.status, 'stage=', j1.values?.stage?.value);
const o2 = await fetch(API + '/api/records/' + acme.id + '/move', { method: 'PATCH', headers: OH, body: JSON.stringify({ attributeKey: 'stage', value: 'qualification' }) }); const j2 = await o2.json(); console.log('OWNER move->qualification:', o2.status, 'stage=', j2.values?.stage?.value);
const g = await fetch(API + '/api/records?objectKey=deals&limit=1', { headers: MH }); console.log('MEMBER GET records:', g.status, '(token valid if 200)');
const mMove = await fetch(API + '/api/records/' + acme.id + '/move', { method: 'PATCH', headers: MH, body: JSON.stringify({ attributeKey: 'stage', value: 'lead' }) }); const jm = await mMove.json(); console.log('MEMBER move->lead:', mMove.status, JSON.stringify(jm));
const after = await (await fetch(API + '/api/records?objectKey=deals&limit=100', { headers: OH })).json();
console.log('Acme stage after MEMBER attempt:', after.records.find((r) => r.id === acme.id)?.values?.stage?.value, '(must stay qualification)');
const acts = await (await fetch(API + '/api/records/' + acme.id + '/activities?limit=3', { headers: OH })).json();
console.log('recent activities:', JSON.stringify((acts.activities || acts || []).slice(0, 3).map((a) => a.title)));
await p.$disconnect();
